# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PyInstaller release for Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        pip install pyinstaller
    - name: Make pyinstaller release
      run: |
        pyinstaller ./helix/main.py --clean -y --collect-all helix --log-level=WARN --add-data ./helix/metadata/*.*:./helix/metadata --add-data ./helix/metadata/report_templates/*.*:./helix/metadata/report_templates --windowed --onefile
    - uses: actions/upload-artifact@v2
      with:
        name: Helix
        path: ./dist/main
        retention-days: 1
